### ISSUE TITLE
ERC20 backward compatiability

### ISSUE THREAD

**Issue by hujw77** [ATNIO/atn-contracts#4]
https://github.com/ATNIO/atn-contracts/blob/9f26b55aad5dbdb7aa01102caa14e73e51f4dcdb/src/ATN.sol#L34

Due to backwards compatibility

function transfer(address _to, uint _value) returns (bool success)

bytes memory empty;
_to.call(bytes4(keccak256("tokenFallback(address,uint256, bytes)")), _from, _amount,empty)

"transfer" could add the interface

**Comment by hackfisher** [comment]
tranfer is calling transferFrom
